

export const DROPDOWN_POS='DROPDOWN_POS';
export const DROPDOWN_TOGGLE='DROPDOWN_TOGGLE';
export const DROPDOWN_SET_IS_OPEN='DROPDOWN_SET_IS_OPEN';
export const MEGAMENU_SET_SELECTED='MEGAMENU_SET_SELECTED'
export const MEGAMENU_GET_SELECTED='MEGAMENU_GET_SELECTED'
