

export const DROPDOWN_POS='DROPDOWN_POS';
export const DROPDOWN_TOGGLE='DROPDOWN_TOGGLE';
export const DROPDOWN_SET_IS_OPEN='DROPDOWN_SET_IS_OPEN';


export const MEGAMENU_SET_SELECTED='MEGAMENU_SET_SELECTED';
export const MEGAMENU_GET_SELECTED='MEGAMENU_GET_SELECTED';


export const MAIN_SET_OVERLAY='MAIN_SET_OVERLAY';
export const MAIN_SET_IS_NAVBAR_OPEN='MAIN_SET_IS_NAVBAR_OPEN';
export const MAIN_SET_LOCATION='MAIN_SET_LOCATION';
export const MAIN_GET_LOCATION='MAIN_GET_LOCATION';
export const MAIN_SET_SHOW_HEADER_AND_FOOTER='MAIN_SET_SHOW_HEADER_AND_FOOTER';
export const MAIN_SET_CURRENT_USER= 'MAIN_SET_CURRENT_USER';
export const MAIN_SET_POPUP= 'MAIN_SET_POPUP';
export const MAIN_SET_TOAST= 'MAIN_SET_TOAST';
export const MAIN_SET_LOADING= 'MAIN_SET_LOADING';
export const MAIN_SET_SIDE_BAR= 'MAIN_SET_SIDE_BAR';
export const MAIN_SET_FILTER_SIDE_BAR= 'MAIN_SET_FILTER_SIDE_BAR';


export const PRODUCTS_GET_ALL='PRODUCTS_GET_ALL';
export const PRODUCTS_GET='PRODUCTS_GET';


export const FILTERS_SET='FILTERS_SET';



